apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
spec:
  controller:
    enabled: false
  argoCDAgent:
    principal:
      enabled: true
      server:
        auth: "mtls:CN=([^,]+)"
        logLevel: "trace"
      namespace:
        allowedNamespaces:
          - "*"
      resourceProxy:
        enable: true
      tls:
        server:
          insecureGenerate: true   
      jwt:
        insecureGenerate: true     
  sourceNamespaces:
    - "agent-managed"
    - "agent-autonomous"
